name: Build all and and Push -> dockerhub

on:
  push:
    branches:
      - main

  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: livingdevopswithakhilesh
  DOCKERHUB_REPO: livingdevopswithakhilesh/craftista

jobs:
  build-push-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      # Build Catalogue Service
      - name: Build and push Catalogue
        uses: docker/build-push-action@v4
        with:
          context: ./microservices-on-k8s/catalogue
          push: true
          tags: ${{ env.DOCKERHUB_REPO }}:catalogue-latest
          # tags: ${{ env.DOCKERHUB_REPO }}:catalogue-latest,${{ env.DOCKERHUB_REPO }}:catalogue-${{ github.sha }}
      
      # Build Frontend Service
      - name: Build and push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./microservices-on-k8s/frontend
          push: true
          tags: ${{ env.DOCKERHUB_REPO }}:frontend-latest,${{ env.DOCKERHUB_REPO }}:frontend-${{ github.sha }}
      
      # Build Recommendation Service
      - name: Build and push Recommendation
        uses: docker/build-push-action@v4
        with:
          context: ./microservices-on-k8s/recommendation
          push: true
          tags: ${{ env.DOCKERHUB_REPO }}:recommendation-latest,${{ env.DOCKERHUB_REPO }}:recommendation-${{ github.sha }}
      
      # Build Voting Service
      - name: Build and push Voting
        uses: docker/build-push-action@v4
        with:
          context: ./microservices-on-k8s/voting
          push: true
          tags: ${{ env.DOCKERHUB_REPO }}:voting-latest,${{ env.DOCKERHUB_REPO }}:voting-${{ github.sha }}
      
      - name: Generate build summary
        run: |
          echo "# Microservices Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ **Catalogue**: ${{ env.DOCKERHUB_REPO }}:catalogue-latest" >> $GITHUB_STEP_SUMMARY
          echo "✅ **Frontend**: ${{ env.DOCKERHUB_REPO }}:frontend-latest" >> $GITHUB_STEP_SUMMARY
          echo "✅ **Recommendation**: ${{ env.DOCKERHUB_REPO }}:recommendation-latest" >> $GITHUB_STEP_SUMMARY
          echo "✅ **Voting**: ${{ env.DOCKERHUB_REPO }}:voting-latest" >> $GITHUB_STEP_SUMMARY